In [1]:
distance = [10,15,17,26]
time = [.30,0.47,0.55,1.20]

In [2]:
speed = distance / time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

How do we use numpy library?

In [3]:
import numpy as np # np - alias name of numpy 


In [12]:
my_list = [101,102,103,104]

print(type(my_list))



<class 'list'>


In [13]:
my_ndarray = np.array(my_list) # creating a numpy array 

print(type(my_ndarray))

print(my_ndarray)

<class 'numpy.ndarray'>
[101 102 103 104]


In [8]:
nd_distance = np.array([10,15,17,26])
nd_time =np.array([.30,0.47,0.55,1.20])

In [9]:
print(type(nd_distance))
print(type(nd_time))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
nd_speed = nd_distance / nd_time

print(nd_speed)

[33.33333333 31.91489362 30.90909091 21.66666667]


From the above, we could infer that numpy supports element wise operations 

# Attributes of ndarray 

-- ndim , shape, size , dtype

-- attributes are the ones that you can use to get to know about the properties of a ndarray(numpy array)

In [14]:
# we are trying to create a numpy array from a list of lists
np_city = np.array([["Delhi", "Mumbai", "Bangalore", "Chennai"] , ["Kolkata", "Hyderabad","Vishakapatnam","Coimbatore"]])

print(np_city)

[['Delhi' 'Mumbai' 'Bangalore' 'Chennai']
 ['Kolkata' 'Hyderabad' 'Vishakapatnam' 'Coimbatore']]


In [15]:
np_city.ndim  #used to find out the number of dimensions of the numpy array

2

In [19]:
np_city.shape #shpae attribute returns the number of rows and columns present in the numpy array
# in the form of a tuple

(2, 4)

Here (2,4) means that there are 2 rows and 4 columns in the np_city array.

In [20]:
np_city.size # this returns the total number of elements present in the numpy array

8

In [21]:
np_city.dtype

dtype('<U13')

In [16]:
np_city1 = np.array(["Delhi", "Mumbai", "Bangalore", "Chennai"]) # this is just a list of values

In [18]:
np_city1.ndim # attributes do not end with ()

1

In [22]:
np_city1.size

4

In [23]:
np_city1.shape

(4,)

In [24]:
np_city1.dtype

dtype('<U9')

# Basic operations on the Numpy Array

Mathematical : + ,- , * , / , **

Logical : &, | , ~

Comparison : > , < , >=, <= , == , !=

In [28]:
distance_1 = np.array([10,12,15,17,20])
distance_2 = np.array([100,200,300,400,500])
time = np.array([0.3,0.45,0.25,0.5,0.16])

In [26]:
speed = distance / time

In [27]:
print(speed)

[ 33.33333333  26.66666667  60.          34.         125.        ]


In [30]:
sum_distances = distance_1 + distance_2
print(sum_distances)

[110 212 315 417 520]


In [42]:
distance_1 * distance_2 # the two numpy arrays used should be of equal size 

array([ 1000,  2400,  4500,  6800, 10000])

# Broadcasting 

In [40]:
print(distance_1)

[10 12 15 17 20]


In [41]:
distance_1 * 2 #the numpy array is multiplied with a single scalar value

array([20, 24, 30, 34, 40])

In [43]:
distance_1 / 5 # in the case of a numpy array, the value gets broadcasted

array([2. , 2.4, 3. , 3.4, 4. ])

In [44]:
distance_1 + 3

array([13, 15, 18, 20, 23])

In [45]:
distance_1 - 10

array([ 0,  2,  5,  7, 10])

In [46]:
list_nums = [1,2,3,4]

In [47]:
list_nums * 2 # this is what happens with a list 

[1, 2, 3, 4, 1, 2, 3, 4]

# How to access array elements using Indexing?

In [48]:
dist_covered = np.array([[2,4,6,8],[3,6,9,12]])

print("The distance covered by the 2 cars in 4 different rides are: ")
print("-------------------------------------------------------------")
print(dist_covered)


The distance covered by the 2 cars in 4 different rides are: 
-------------------------------------------------------------
[[ 2  4  6  8]
 [ 3  6  9 12]]


In [49]:
dist_covered[0,0]

2

In [50]:
dist_covered[0] # this would retrieve all the values of row 1 

array([2, 4, 6, 8])

In [51]:
dist_covered[1,2]

9

In [52]:
dist_covered[0,:] # the value in the first position indicates the index value of the rows
# the value in the second position indicates the index of the columns

# : -- means to select everything 

array([2, 4, 6, 8])

In [54]:
dist_covered[1,1:]

array([ 6,  9, 12])

In [55]:
dist_covered[:,2:] # index_num: --> select all the values from the specified index value until the end 

array([[ 6,  8],
       [ 9, 12]])

In [56]:
dist_covered[:,0:2]   # 0:2 , 0 is the start index.so,it's inclusive.
                      # 2 is the end index. so, it's inclusive only until 2-1 = 1 
    #Hence, the values present in the first and second columns are retrieved

array([[2, 4],
       [3, 6]])

In [57]:
dist_covered[:,:2] # :2 means - selecting all the values until (2-1) in the column which means
# that only the values present in the 0th and 1th columns of both the rows would be retrieved

array([[2, 4],
       [3, 6]])

# Conditional Selection

In [58]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [59]:
dist_covered > 5  # whenever you use comparison aperations on numpy arrays, it would always return 
#only a boolean set of values

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [60]:
dist_covered[dist_covered > 5] # within the square braces , instead of the index, if you pass the condition, 
#it is called "Conditional Selection"

array([ 6,  8,  6,  9, 12])

In [61]:
dist_covered[dist_covered == 6]  # equal to condition

array([6, 6])

In [62]:
dist_covered[dist_covered == 6].size # this would give you the number of rides that had covered 6 kms

2

In [63]:
dist_covered[dist_covered != 6]  # not equal to condition

array([ 2,  4,  8,  3,  9, 12])

In [66]:
print("The total number of rides in which the total distance covered is not equal to 6 kms is :")
dist_covered[dist_covered != 6].size

The total number of rides in which the total distance covered is not equal to 6 kms is :


6

In [64]:
dist_covered[dist_covered >= 6 ]  #greater than and equal to condtion

array([ 6,  8,  6,  9, 12])

In [67]:
dist_covered[dist_covered > 6 ]  

array([ 8,  9, 12])

In [68]:
dist_covered[dist_covered <= 6 ]

array([2, 4, 6, 3, 6])

In [69]:
dist_covered[dist_covered < 6 ]  

array([2, 4, 3])

In [73]:
dist_covered[(dist_covered < 6) & (dist_covered > 3) ] # using logical & comparison operators 

array([4])

In [74]:
dist_covered[~(dist_covered < 6)] # making use of logical not operator

array([ 6,  8,  6,  9, 12])

# Universal Functions - Ufunc

In [78]:
num_array = np.array([4,9,16,25,36])

In [79]:
print("Square root of the num_array values are : ")

print(np.sqrt(num_array))

Square root of the num_array values are : 
[2. 3. 4. 5. 6.]


In [80]:
print("Average (mean) value of the num_array is :")

print(np.mean(num_array))

Average (mean) value of the num_array is :
18.0


In [81]:
print("Standard Deviation of the num_array values is: ")
print(np.std(num_array))

Standard Deviation of the above numbers are: 
11.436782764396638


In [82]:
print("Variance of the num_array values are: ")
print(np.var(num_array))

Variance of the num_array values are: 
130.8


In [83]:
print("Median value of the num_array is: ")
print(np.median(num_array))

Median value of the num_array is: 
16.0


In [85]:
print("Sum of all the values of the num_array is :")

print(np.sum(num_array))

Sum of all the values of the num_array is :
90


In [86]:
num_array2 = np.array([1.75, 2.6, 3.4])

say, we want to round off values. We can do that either using the floor function or the ceil function

In [87]:
np.floor([num_array2]) # the values are floored down to the nearest previous numbers

array([[1., 2., 3.]])

In [88]:
np.ceil([num_array2]) # the values are ceiled up to the nearest next numbers

array([[2., 3., 4.]])

# Shape Manipulation

-- flatten the array , resize the array, split the array, stack the array, reshape the array

In [89]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [90]:
dist_covered.shape

(2, 4)

In [91]:
dist_covered.ravel() # this method is used to flatten the array to a 1-dimensional array.

array([ 2,  4,  6,  8,  3,  6,  9, 12])

Kindly remember that what you see above is just a view of what the ravel() method could do to your data and that it doesn't affect your original data until you assign this to the original data variable.

In [92]:
dist_covered.ravel().ndim

1

In [95]:
dist_covered_ravel = dist_covered.ravel() 

dist_covered_ravel

array([ 2,  4,  6,  8,  3,  6,  9, 12])

In [93]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [96]:
dist_covered.reshape(1,8)

array([[ 2,  4,  6,  8,  3,  6,  9, 12]])

In [97]:
dist_covered.reshape(8,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [12]])

In [98]:
dist_covered.reshape(4,2)  # does not affect the original array (i.e) it is a temporary change

array([[ 2,  4],
       [ 6,  8],
       [ 3,  6],
       [ 9, 12]])

In [100]:
dist_covered.resize(1,8) # affects the original array (i.e) it is a permanent change

In [101]:
dist_covered

array([[ 2,  4,  6,  8,  3,  6,  9, 12]])

In [103]:
dist_covered.resize(2,4)

print(dist_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


# How to split the numpy array?

-- hsplit , vsplit

In [104]:
np.hsplit(dist_covered , 2) # splits the array column wise 

# hplit - horizontal split

[array([[2, 4],
        [3, 6]]), array([[ 6,  8],
        [ 9, 12]])]

In [105]:
np.hsplit(dist_covered , 3)

ValueError: array split does not result in an equal division

we can infer from above that hsplit results only in equal sized sub-arrays

In [106]:
np.vsplit(dist_covered , 2) # vsplit is used to split the array along the rows 

# vsplit - vertical split

[array([[2, 4, 6, 8]]), array([[ 3,  6,  9, 12]])]

# stacking the values of numpy arrays - hstack, vstack

In [108]:
print(dist_covered)
print("---------------")
dist_covered3 = np.array([[1,2,3,4],[15,16,17,18]])

print(dist_covered3)
print("---------------")


[[ 2  4  6  8]
 [ 3  6  9 12]]
---------------
[[ 1  2  3  4]
 [15 16 17 18]]
---------------


In [109]:
print("The stacked arrays using hstack: ")
print(np.hstack((dist_covered,dist_covered3))) # hstack adds the number of columns

The stacked arrays using hstack: 
[[ 2  4  6  8  1  2  3  4]
 [ 3  6  9 12 15 16 17 18]]


In [110]:
print("The stacked arrays using vstack: ")
print(np.vstack((dist_covered,dist_covered3))) # vstack adds the number of rows

The stacked arrays using vstack: 
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [15 16 17 18]]


In [111]:
dist_covered2 = np.array([[2,4,6,8],[3,6,9,12],[1,2,3,4],[15,16,17,18]])

dist_covered2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 1,  2,  3,  4],
       [15, 16, 17, 18]])

In [112]:
print(dist_covered)

print("--------------")

print(dist_covered2)
print("--------------")

np.hstack((dist_covered,dist_covered2)) # hstack is not possible because the number of rows is not same in both

[[ 2  4  6  8]
 [ 3  6  9 12]]
--------------
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [15 16 17 18]]
--------------


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

will vstack be possible?  -- **yes**

In [113]:
np.vstack((dist_covered,dist_covered2)) # vstack is possible it maintains the same number of 
#columns and just increases the number of rows 

#since both the arrays have the same number of columns, vstack is possible here.

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 1,  2,  3,  4],
       [15, 16, 17, 18]])

# generating numpy arrays using in built numpy methods 

-- arange, linspace , randint , randn , rand

**arange** 

-- Returns evenly spaced values within a given interval as input.


In [114]:
np.arange(0,20) # by default, arange generates equally spaced values with an interval of 1.

# always the end limit value is inclusive only until (end_limit_value - 1 )

# by default, this method would generate only integer values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
np.arange(0,20 , dtype = 'float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [116]:
np.arange(0,20,4) # first value - start limit , second value - stop limit , third value - step value

array([ 0,  4,  8, 12, 16])

In [118]:
np.arange(5,20,5)

array([ 5, 10, 15])

In [119]:
np.arange(0,20, 2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [120]:
np.arange(10,101,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**linspace**

-- Return evenly spaced numbers over a specified interval.

In [121]:
np.linspace(1,10, 5) # both the start and stop limits are inclusive in linspace

# and the third parameter here, specifies the number of values to be generated within the given 
# start and stop limits

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [122]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

we can infer from the above that linspace has generated 100 equally spaced values within the limits - 0 , 20

In [125]:
np.linspace(1,10,5, dtype= "int")

array([ 1,  3,  5,  7, 10])

# How to generate random arrays using numpy methods ? 

Numpy has lots of options to create random numbered arrays:

**rand**

Create an array of the given shape and populate it with random variables derived from a uniform distribution between [0, 1).

In [126]:
np.random.rand(5)

array([0.3054971 , 0.70096537, 0.42576606, 0.71317915, 0.21983496])

In [127]:
np.random.rand(3,2) # this would generate a random number array with 3 rows and 2 columns 

# also mind that the values here are selected in random by the rand method from the uniform
#distribution between 0 and 1

array([[0.59693472, 0.7133784 ],
       [0.05353133, 0.3637545 ],
       [0.57857912, 0.85464396]])

**randn**

Return a variable (or a set of variables) from the "Standard Normal" distribution. Unlike rand which is from a uniform distribution:

A standard Normal Distribution has mean 0 and SD of 1 as we know.

In [129]:
np.random.randn(5)

array([ 1.42920967,  1.63131037, -0.65422055,  0.6053747 ,  0.17189549])

In [130]:
np.random.randn(3,2) 

array([[-0.58139213, -2.27492322],
       [-0.5249181 ,  2.18567957],
       [ 0.56795186, -0.61914442]])

**randint**

-- Return random integers from low (inclusive) to high (exclusive).

In [135]:
np.random.randint(5,20) # by default this will generate one random number between the specified limits

16

In [136]:
np.random.randint(5,20,3) # this will generate 3 random integer numbers within the given limits - 5,20

array([17,  8, 12])

In [137]:
np.random.randint(20,50,10)

array([28, 33, 36, 37, 35, 39, 49, 36, 20, 34])

# End of Numpy discussion