In [1]:
distance = [10,15,17,26]
time = [.30,0.47,0.55,1.20]

In [2]:
speed = distance / time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

How do we use numpy library?

In [3]:
import numpy as np # np - alias name of numpy 


In [12]:
my_list = [101,102,103,104]

print(type(my_list))



<class 'list'>


In [13]:
my_ndarray = np.array(my_list) # creating a numpy array 

print(type(my_ndarray))

print(my_ndarray)

<class 'numpy.ndarray'>
[101 102 103 104]


In [8]:
nd_distance = np.array([10,15,17,26])
nd_time =np.array([.30,0.47,0.55,1.20])

In [9]:
print(type(nd_distance))
print(type(nd_time))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
nd_speed = nd_distance / nd_time

print(nd_speed)

[33.33333333 31.91489362 30.90909091 21.66666667]


From the above, we could infer that numpy supports element wise operations 

# Attributes of ndarray 

-- ndim , shape, size , dtype

-- attributes are the ones that you can use to get to know about the properties of a ndarray(numpy array)

In [14]:
# we are trying to create a numpy array from a list of lists
np_city = np.array([["Delhi", "Mumbai", "Bangalore", "Chennai"] , ["Kolkata", "Hyderabad","Vishakapatnam","Coimbatore"]])

print(np_city)

[['Delhi' 'Mumbai' 'Bangalore' 'Chennai']
 ['Kolkata' 'Hyderabad' 'Vishakapatnam' 'Coimbatore']]


In [15]:
np_city.ndim  #used to find out the number of dimensions of the numpy array

2

In [19]:
np_city.shape #shpae attribute returns the number of rows and columns present in the numpy array
# in the form of a tuple

(2, 4)

Here (2,4) means that there are 2 rows and 4 columns in the np_city array.

In [20]:
np_city.size # this returns the total number of elements present in the numpy array

8

In [21]:
np_city.dtype

dtype('<U13')

In [16]:
np_city1 = np.array(["Delhi", "Mumbai", "Bangalore", "Chennai"]) # this is just a list of values

In [18]:
np_city1.ndim # attributes do not end with ()

1

In [22]:
np_city1.size

4

In [23]:
np_city1.shape

(4,)

In [24]:
np_city1.dtype

dtype('<U9')

# Basic operations on the Numpy Array

Mathematical : + ,- , * , / , **

Logical : &, | , ~

Comparison : > , < , >=, <= , == , !=

In [28]:
distance_1 = np.array([10,12,15,17,20])
distance_2 = np.array([100,200,300,400,500])
time = np.array([0.3,0.45,0.25,0.5,0.16])

In [26]:
speed = distance / time

In [27]:
print(speed)

[ 33.33333333  26.66666667  60.          34.         125.        ]


In [30]:
sum_distances = distance_1 + distance_2
print(sum_distances)

[110 212 315 417 520]


In [42]:
distance_1 * distance_2 # the two numpy arrays used should be of equal size 

array([ 1000,  2400,  4500,  6800, 10000])

# Broadcasting 

In [40]:
print(distance_1)

[10 12 15 17 20]


In [41]:
distance_1 * 2 #the numpy array is multiplied with a single scalar value

array([20, 24, 30, 34, 40])

In [43]:
distance_1 / 5 # in the case of a numpy array, the value gets broadcasted

array([2. , 2.4, 3. , 3.4, 4. ])

In [44]:
distance_1 + 3

array([13, 15, 18, 20, 23])

In [45]:
distance_1 - 10

array([ 0,  2,  5,  7, 10])

In [46]:
list_nums = [1,2,3,4]

In [47]:
list_nums * 2 # this is what happens with a list 

[1, 2, 3, 4, 1, 2, 3, 4]

# How to access array elements using Indexing?

In [48]:
dist_covered = np.array([[2,4,6,8],[3,6,9,12]])

print("The distance covered by the 2 cars in 4 different rides are: ")
print("-------------------------------------------------------------")
print(dist_covered)


The distance covered by the 2 cars in 4 different rides are: 
-------------------------------------------------------------
[[ 2  4  6  8]
 [ 3  6  9 12]]


In [49]:
dist_covered[0,0]

2

In [50]:
dist_covered[0] # this would retrieve all the values of row 1 

array([2, 4, 6, 8])

In [51]:
dist_covered[1,2]

9

In [52]:
dist_covered[0,:] # the value in the first position indicates the index value of the rows
# the value in the second position indicates the index of the columns

# : -- means to select everything 

array([2, 4, 6, 8])

In [54]:
dist_covered[1,1:]

array([ 6,  9, 12])

In [55]:
dist_covered[:,2:] # index_num: --> select all the values from the specified index value until the end 

array([[ 6,  8],
       [ 9, 12]])

In [56]:
dist_covered[:,0:2]   # 0:2 , 0 is the start index.so,it's inclusive.
                      # 2 is the end index. so, it's inclusive only until 2-1 = 1 
    #Hence, the values present in the first and second columns are retrieved

array([[2, 4],
       [3, 6]])

In [57]:
dist_covered[:,:2] # :2 means - selecting all the values until (2-1) in the column which means
# that only the values present in the 0th and 1th columns of both the rows would be retrieved

array([[2, 4],
       [3, 6]])

# Conditional Selection

In [58]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [59]:
dist_covered > 5  # whenever you use comparison aperations on numpy arrays, it would always return 
#only a boolean set of values

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [60]:
dist_covered[dist_covered > 5] # within the square braces , instead of the index, if you pass the condition, 
#it is called "Conditional Selection"

array([ 6,  8,  6,  9, 12])

In [61]:
dist_covered[dist_covered == 6]  # equal to condition

array([6, 6])

In [62]:
dist_covered[dist_covered == 6].size # this would give you the number of rides that had covered 6 kms

2

In [63]:
dist_covered[dist_covered != 6]  # not equal to condition

array([ 2,  4,  8,  3,  9, 12])

In [66]:
print("The total number of rides in which the total distance covered is not equal to 6 kms is :")
dist_covered[dist_covered != 6].size

The total number of rides in which the total distance covered is not equal to 6 kms is :


6

In [64]:
dist_covered[dist_covered >= 6 ]  #greater than and equal to condtion

array([ 6,  8,  6,  9, 12])

In [67]:
dist_covered[dist_covered > 6 ]  

array([ 8,  9, 12])

In [68]:
dist_covered[dist_covered <= 6 ]

array([2, 4, 6, 3, 6])

In [69]:
dist_covered[dist_covered < 6 ]  

array([2, 4, 3])

In [73]:
dist_covered[(dist_covered < 6) & (dist_covered > 3) ] # using logical & comparison operators 

array([4])

In [74]:
dist_covered[~(dist_covered < 6)] # making use of logical not operator

array([ 6,  8,  6,  9, 12])